name: Upload file to remote server
 on: [push]
 jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
     steps:
       - name: Upload file to remote server
         uses: appleboy/ssh-action@v1
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           script: cd /var/www/dansl.net/pages && wget -O macos.md https://raw.githubusercontent.com/dansl/MacOS-Stuff/refs/heads/main/README.md &&  git commit -a -m "updated macos.md" && gh repo sync 
